name: JAR_build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Clone project
        run: |
          git clone --depth=1 https://github.com/UFR6cRY9xufLKtx2idrc/glide

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build and run unit tests with Gradle
        working-directory: glide
        run: ./scripts/ci_unit.sh

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: avif-integration
          path: project/glide/integration/avif/target/*.jar
          if-no-files-found: error

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: project/glide/integration/avif/target/*.jar
          asset_name: avif-integration-${{ github.run_number }}.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
