name: android_build

on:
  push:
    branches:
      - main
    paths:
      - "**/project-to-build"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true
        
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Clone project
        run: |
          git clone --depth=1 https://codeberg.org/NullPointerException/PipePipe project/PipePipe
          git clone --depth=1 https://codeberg.org/NullPointerException/PipePipeClient project/PipePipeClient
          git clone --depth=1 https://codeberg.org/NullPointerException/PipePipeExtractor project/PipePipeExtractor
        
      - name: Build the app
        working-directory: ./project
        run: |
          cd PipePipeClient
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleRelease --stacktrace

      - name: Create 7z Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./project/PipePipeClient/app/build/outputs/apk/release/
          pathTarget: ./release.7z

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: my-build-apk.7z
          path: release.7z
          if-no-files-found: error

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release.7z
          asset_name: my-build-apk-${{ github.run_number }}.7z
          tag: ${{ github.ref }}
          overwrite: true
