name: JAR_build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Clone project
        run: |
          git clone --depth=1 --branch=master https://github.com/bumptech/glide.git
          cd glide
          git revert 193cf61354cc01f38b15bf1605905b49a19e6b7a^..46eb7311b2c75ac015e56fa165e6c99e757d0a71
          git branch -a
          git remote add glide2 https://github.com/bumptech/glide
          git remote
          git fetch glide2
          git branch -a
          git checkout master
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git cherry-pick 06fc8f689c0936ee570ed3e31ae2d6a1ff019fe9
          git cherry-pick 3bbc3908edd8432f55ccfae3257bad533c1bf7d1
          git push origin --delete glide2

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build and run unit tests with Gradle
        working-directory: glide
        run: ./scripts/ci_unit.sh

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: avif-integration
          path: /home/runner/work/builder/builder/glide/integration/avif/build/outputs/aar/avif-release.aar
          if-no-files-found: error

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/builder/builder/glide/integration/avif/build/outputs/aar/avif-release.aar
          asset_name: avif-integration-${{ github.run_number }}.aar
          tag: ${{ github.ref }}
          overwrite: true
