name: JAR_build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Clone project
        run: |
          git clone --depth=1 --branch=compose-alpha6 https://github.com/bumptech/glide.git

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build and run unit tests with Gradle
        working-directory: glide
        run: ./scripts/ci_unit.sh

      - name: Create 7z Release
        uses: DuckSoft/create-7z-action@v1.0
        with:
          pathSource: ./project/glide/
          pathTarget: ./glide.7z

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: glide.7z
          path: glide.7z
          if-no-files-found: error

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: glide.7z
          asset_name: glide-${{ github.run_number }}.7z
          tag: ${{ github.ref }}
          overwrite: true
