name: JAR_build

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 11
          check-latest: true

      - name: Clone project
        run: |
          git clone --depth=1 --branch=master https://github.com/bumptech/glide.git
          cd glide
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git revert 193cf61354cc01f38b15bf1605905b49a19e6b7a
          git revert fcace5be3c7edbc85af99183b64438997051b06c
          git revert 8ca2db2e898cf3c7acfd9de6a310ff4ec40d10dc
          git revert e85c7656ccb908ab0bb6a4fd7706029a51048535
          git revert 35bf5a58ae2a7662c1cdec8dab06d48795dba7d2
          git revert 17620f51ddef06cbf96ea6fcfad137fd51332fd5
          git revert e77562a432352da19741d93b8c1f6599b558676a
          git revert c06a85d8427de557a1a04e0370e44007301bcf9b
          git revert 75599b7af05eeca1393c8f4267adb78e88e7821e
          git revert b1c6076bbbc3cc46d45f35924070cb11be44ff90
          git revert 1863e6713a34507f584c4d1f2a061dd885b687ee
          git revert f0d2b16034826757e4c68e5320b7707a8d43a289
          git revert b3fd2bc1b68b988202e50fac757a318274c16be8
          git revert 05d346557c284844fb85eedbd7c7db009591f0e8
          git revert 9809d98fe43ae3d0593f3d710bb32af9bed72642
          git revert e8d10fc3dabdb835be1db3779e961064ffec3291
          git revert efc56f8bc03846706027076779cac33d489a680d
          git revert 12c86e9a316bd774b77bc47b7fbed38a146d704b
          git revert fe3b9128d75a9ae43c46b77e72a217ce3fc3e1e5
          git revert bd2a519d7d8095a3a0e307486ddd6ed9bbb84e65
          git revert 69e220463ac7110b87beaa7a0e3e124f38cecacd
          git revert c6960d314151ad6c03e9e5eea5a9dcea57e6035e
          git revert 46eb7311b2c75ac015e56fa165e6c99e757d0a71
          git remote add glide2 https://github.com/bumptech/glide
          git fetch glide2
          git branch -a
          git checkout master
          git cherry-pick 06fc8f689c0936ee570ed3e31ae2d6a1ff019fe9
          git cherry-pick 3bbc3908edd8432f55ccfae3257bad533c1bf7d1
          git push origin --delete glide2

      - name: Gradle Build
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-home-cache-cleanup: true

      - name: Build and run unit tests with Gradle
        working-directory: glide
        run: ./scripts/ci_unit.sh

      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: avif-integration
          path: /home/runner/work/builder/builder/glide/integration/avif/build/outputs/aar/avif-release.aar
          if-no-files-found: error

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/builder/builder/glide/integration/avif/build/outputs/aar/avif-release.aar
          asset_name: avif-integration-${{ github.run_number }}.aar
          tag: ${{ github.ref }}
          overwrite: true
